module.exports = {
  id: ["Submission ID", "ID", "id"],
  firstName: ["First Name", "firstname", "FirstName"],
  lastName: ["Last Name", "lastname", "LastName"],
  dateOfBirth: ["Date of Birth", "DOB", "dob"],
  gender: ["Gender"],
  mobile: ["Mobile Number", "Mobile", "Phone"],
  email: ["Email ID", "Email", "Email Address"],
  country: ["Country"],
  state: ["State"],
  city: ["City"],
  address: ["Address"],
  pincode: ["Pincode", "Postal Code", "Zip"],
  languages: ["Known Language", "Languages"],
  education: ["Education"],
  profession: ["Profession"],
  profilePhoto: ["Profile Photo", "Photo"],
  attendedWorkshop: ["Attended Workshop"],
  vahiniMember: ["Preksha Vahini Member"],
  practicing: ["Currently Practicing", "Practice Status"],
  usesApp: ["Uses App"],
  restartPractice: ["Restart Daily Practice", "Restart Practice"],
  attendOnlineWorkshop: ["Attend Online Workshop"],
  attendResidentialCamp: ["Attend Residential Camp"],
  becomeVolunteer: ["Become Volunteer"],
  becomeFacilitator: ["Become Facilitator"],
  becomeTrainer: ["Become Trainer"],
  helpOrganizeSessions: ["Help Organize Local Sessions", "Help Organize Sessions"],
  needGuidance: ["Need Guidance"],
  preferredOnline: ["Preferred Online", "Online"],
  preferredOfflineCity: ["Preferred Offline City", "Offline In My City"],
  preferredResidentialCamp: ["Preferred Residential Camp"],
  preferredAppPractice: ["Preferred App Practice"],
  supportMessage: ["Support Message"],
  registrationDate: ["Registration Date"]
};
